language: node_js
node_js:
  - "stable"
  - "5.9.1"
  - "5.7.0"
  - "4.4.1"
#  - "0.12" #fails const
#  - "0.10" #fails const
#  - "iojs" #fails
#  - "iojs-v1.1.0" #fails
branches:
  only:
    - master
script:
  - "npm run-script test"
  - "npm run-script cover"
  - "npm run-script lint"
